//! Turns a [`Profile`] subset into Rust source for `zerofit-profile`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::io::Write as _;
use std::process::{Command, Stdio};

use crate::extract::is_enum_type;
use crate::model::{EnumValue, Field, Message, Profile, TypeDef};

/// One generated source file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to `crates/zerofit-profile/src/generated/`.
    pub path: &'static str,
    /// Formatted Rust source.
    pub contents: String,
}

/// Generates the profile layer's source files, formatted with `rustfmt`.
pub fn generate(profile: &Profile) -> Result<Vec<GeneratedFile>, String> {
    let types = TypeTable::new(profile);
    let files = [
        ("types.rs", gen_types(profile, &types)),
        ("messages.rs", gen_messages(profile, &types)?),
    ];
    files
        .into_iter()
        .map(|(path, src)| {
            Ok(GeneratedFile {
                path,
                contents: rustfmt(&src)?,
            })
        })
        .collect()
}

const HEADER: &str = "// @generated by zerofit-codegen from the FIT SDK profile. Do not edit.\n\
// Regenerate with `cargo xtask codegen`. See the crate README for the\n\
// FIT SDK license notice that applies to this file.\n\n";

fn rustfmt(src: &str) -> Result<String, String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("cannot run rustfmt: {e}"))?;
    child
        .stdin
        .take()
        .ok_or("no stdin")?
        .write_all(src.as_bytes())
        .map_err(|e| e.to_string())?;
    let out = child.wait_with_output().map_err(|e| e.to_string())?;
    if !out.status.success() {
        return Err(format!(
            "rustfmt failed:\n{}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    String::from_utf8(out.stdout).map_err(|e| e.to_string())
}

/// How a profile type maps to Rust.
#[derive(Debug, Clone)]
enum Kind {
    /// A generated enum with the given raw integer type.
    Enum {
        name: String,
        raw: &'static str,
    },
    Int(&'static str),
    Float,
    Bool,
    String,
    Bytes,
}

struct TypeTable<'p> {
    types: BTreeMap<&'p str, &'p TypeDef>,
}

impl<'p> TypeTable<'p> {
    fn new(profile: &'p Profile) -> Self {
        Self {
            types: profile.types.iter().map(|t| (t.name.as_str(), t)).collect(),
        }
    }

    fn kind(&self, profile_type: &str) -> Result<Kind, String> {
        if profile_type == "bool" {
            return Ok(Kind::Bool);
        }
        if let Some(ty) = self.types.get(profile_type) {
            let raw = base_int(&ty.base_type)
                .ok_or_else(|| format!("type {profile_type} has base {}", ty.base_type))?;
            return Ok(if is_enum_type(ty) {
                Kind::Enum {
                    name: format!("types::{}", camel(profile_type)),
                    raw,
                }
            } else {
                Kind::Int(raw)
            });
        }
        Ok(match profile_type {
            "string" => Kind::String,
            "byte" => Kind::Bytes,
            "float32" | "float64" => Kind::Float,
            other => Kind::Int(base_int(other).ok_or_else(|| format!("unknown type {other}"))?),
        })
    }
}

fn base_int(base: &str) -> Option<&'static str> {
    Some(match base {
        "enum" | "uint8" | "uint8z" => "u8",
        "sint8" => "i8",
        "uint16" | "uint16z" => "u16",
        "sint16" => "i16",
        "uint32" | "uint32z" => "u32",
        "sint32" => "i32",
        "uint64" | "uint64z" => "u64",
        "sint64" => "i64",
        _ => return None,
    })
}

/// `snake_case` to `CamelCase`; a leading digit gets an `N` prefix.
fn camel(s: &str) -> String {
    let mut out = String::new();
    for part in s.split('_').filter(|p| !p.is_empty()) {
        let mut chars = part.chars();
        if let Some(c) = chars.next() {
            out.extend(c.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, 'N');
    }
    out
}

/// A field name as a method name.
fn method(s: &str) -> String {
    const RESERVED: &[&str] = &[
        "type", "match", "self", "fn", "mod", "use", "ref", "move", "loop", "new", "raw",
    ];
    if RESERVED.contains(&s) {
        format!("{s}_")
    } else {
        s.to_owned()
    }
}

/// Makes profile text safe inside a doc comment: no intra-doc links or HTML.
fn doc_text(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('*', "\\*")
        .replace('_', "\\_")
        .replace("\r\n", " ")
        .replace(['\n', '\r'], " ")
}

fn float_lit(v: f64) -> String {
    format!("{v:?}")
}

// ---------------------------------------------------------------- types.rs

fn gen_types(profile: &Profile, types: &TypeTable<'_>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("//! Profile types used by the generated messages.\n\n");
    let mesg_num = TypeDef {
        name: "mesg_num".into(),
        base_type: "uint16".into(),
        values: profile.mesg_num.clone(),
    };
    gen_enum(&mut out, &mesg_num, "u16", &profile.sdk_version);
    for ty in types.types.values() {
        if is_enum_type(ty) {
            let raw = base_int(&ty.base_type).unwrap_or("u8");
            gen_enum(&mut out, ty, raw, &profile.sdk_version);
        }
    }
    out
}

fn gen_enum(out: &mut String, ty: &TypeDef, raw: &str, sdk: &str) {
    let name = camel(&ty.name);
    // Keep the first name for each value; later names are aliases.
    let mut seen_values = BTreeSet::new();
    let mut seen_names = BTreeSet::new();
    let mut variants: Vec<(String, &EnumValue)> = Vec::new();
    for v in &ty.values {
        if !seen_values.insert(v.value) {
            continue;
        }
        let mut variant = camel(&v.name);
        if variant == "Unrecognized" || !seen_names.insert(variant.clone()) {
            variant = format!("{variant}{}", v.value);
            seen_names.insert(variant.clone());
        }
        variants.push((variant, v));
    }

    let _ = writeln!(
        out,
        "/// The `{}` profile type (base type `{}`).\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n\
         #[non_exhaustive]\npub enum {name} {{",
        ty.name, ty.base_type
    );
    for (variant, v) in &variants {
        let comment = v
            .comment
            .as_deref()
            .map(|c| format!(": {}", doc_text(c)))
            .unwrap_or_default();
        let _ = writeln!(
            out,
            "    /// `{}` ({}){comment}\n    {variant},",
            v.name, v.value
        );
    }
    let _ = writeln!(
        out,
        "    /// A value with no name in FIT profile {sdk}.\n    Unrecognized({raw}),\n}}\n"
    );

    let _ = writeln!(out, "impl {name} {{");
    let _ = writeln!(
        out,
        "    /// Maps a raw value to its variant.\n    #[must_use]\n    \
         pub const fn from_raw(raw: {raw}) -> Self {{\n        match raw {{"
    );
    for (variant, v) in &variants {
        let _ = writeln!(out, "            {} => Self::{variant},", v.value);
    }
    let _ = writeln!(
        out,
        "            other => Self::Unrecognized(other),\n        }}\n    }}\n"
    );
    let _ = writeln!(
        out,
        "    /// The raw value.\n    #[must_use]\n    \
         pub const fn to_raw(self) -> {raw} {{\n        match self {{"
    );
    for (variant, v) in &variants {
        let _ = writeln!(out, "            Self::{variant} => {},", v.value);
    }
    let _ = writeln!(
        out,
        "            Self::Unrecognized(raw) => raw,\n        }}\n    }}\n"
    );
    let _ = writeln!(
        out,
        "    /// The profile's name for this value, or `None` if unrecognized.\n    \
         #[must_use]\n    pub const fn name(self) -> Option<&'static str> {{\n        \
         Some(match self {{"
    );
    for (variant, v) in &variants {
        let _ = writeln!(out, "            Self::{variant} => \"{}\",", v.name);
    }
    let _ = writeln!(
        out,
        "            Self::Unrecognized(_) => return None,\n        }})\n    }}\n}}\n"
    );
}

// ------------------------------------------------------------- messages.rs

fn gen_messages(profile: &Profile, types: &TypeTable<'_>) -> Result<String, String> {
    let mut out = String::from(HEADER);
    out.push_str(
        "//! Typed views of the profile messages covered by this crate.\n\n\
         use zerofit::{DataMessage, FitStr};\n\n\
         use super::types;\n\
         use crate::{Elements, FieldInfo, MessageInfo, read};\n\n",
    );
    for message in &profile.messages {
        gen_message(&mut out, message, types)?;
    }
    gen_dispatch(&mut out, &profile.messages);
    gen_info(&mut out, &profile.messages)?;
    Ok(out)
}

fn gen_message(out: &mut String, message: &Message, types: &TypeTable<'_>) -> Result<(), String> {
    let name = camel(&message.name);
    let _ = writeln!(
        out,
        "/// The `{}` message (global message number {}).\n///\n\
         /// Accessors return `None` when the field is absent or holds the\n\
         /// invalid value. Scaled fields are returned in their profile units.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct {name}<'a>(pub(crate) DataMessage<'a>);\n\n\
         impl<'a> {name}<'a> {{\n    \
         /// Global message number of `{}`.\n    pub const GLOBAL: u16 = {};\n\n    \
         /// Wraps `msg` if it is a `{}` message.\n    #[must_use]\n    \
         pub fn new(msg: DataMessage<'a>) -> Option<Self> {{\n        \
         (msg.global_message_number() == Self::GLOBAL).then_some(Self(msg))\n    }}\n\n    \
         /// The underlying raw message.\n    #[must_use]\n    \
         pub const fn raw(&self) -> &DataMessage<'a> {{\n        &self.0\n    }}\n",
        message.name, message.number, message.name, message.number, message.name
    );
    for field in &message.fields {
        gen_accessor(out, field, types)?;
    }
    out.push_str("}\n\n");
    Ok(())
}

fn gen_accessor(out: &mut String, field: &Field, types: &TypeTable<'_>) -> Result<(), String> {
    let n = field.number;
    let kind = types.kind(&field.field_type)?;
    let scaling = field.single_scale_offset();
    let units = field
        .units
        .as_deref()
        .map(|u| format!(", in {}", doc_text(u)))
        .unwrap_or_default();
    let mut doc = format!(
        "`{}` (field {n}, type `{}`{units}).",
        field.name, field.field_type
    );
    if let Some((scale, offset)) = scaling {
        let _ = write!(
            doc,
            " Scaled: raw / {} - {}.",
            float_lit(scale),
            float_lit(offset)
        );
    }
    if let Some(comment) = &field.comment {
        let _ = write!(doc, "\n    ///\n    /// {}", doc_text(comment));
    }
    let numeric = matches!(
        kind,
        Kind::Int(_) | Kind::Enum { .. } | Kind::Float | Kind::Bool
    );
    let (ret, body) = if field.array.is_some() && numeric {
        let (scale, offset) = scaling.unwrap_or((1.0, 0.0));
        doc.push_str("\n    ///\n    /// An array: yields each valid element as `f64`, scaled.");
        (
            "Elements<'a>".to_owned(),
            format!(
                "read::elements(&self.0, {n}, {}, {})",
                float_lit(scale),
                float_lit(offset)
            ),
        )
    } else if field.array.is_some() && !matches!(kind, Kind::Bytes) {
        (
            "Option<zerofit::Value<'a>>".to_owned(),
            format!("read::raw(&self.0, {n})"),
        )
    } else if let (Some((scale, offset)), true) = (scaling, numeric) {
        (
            "Option<f64>".to_owned(),
            format!(
                "read::scaled(&self.0, {n}, {}, {})",
                float_lit(scale),
                float_lit(offset)
            ),
        )
    } else {
        match kind {
            Kind::Enum { name, raw } => (
                format!("Option<{name}>"),
                format!("read::int::<{raw}>(&self.0, {n}).map({name}::from_raw)"),
            ),
            Kind::Int(raw) => (format!("Option<{raw}>"), format!("read::int(&self.0, {n})")),
            Kind::Float => (
                "Option<f64>".to_owned(),
                format!("read::float(&self.0, {n})"),
            ),
            Kind::Bool => (
                "Option<bool>".to_owned(),
                format!("read::int::<u8>(&self.0, {n}).map(|v| v != 0)"),
            ),
            Kind::String => (
                "Option<FitStr<'a>>".to_owned(),
                format!("read::string(&self.0, {n})"),
            ),
            Kind::Bytes => (
                "Option<&'a [u8]>".to_owned(),
                format!("read::bytes(&self.0, {n})"),
            ),
        }
    };
    let _ = writeln!(
        out,
        "\n    /// {doc}\n    #[must_use]\n    pub fn {}(&self) -> {ret} {{\n        {body}\n    }}",
        method(&field.name)
    );
    Ok(())
}

fn gen_dispatch(out: &mut String, messages: &[Message]) {
    out.push_str(
        "/// A data message, typed if this crate covers its message.\n\
         ///\n/// ```\n\
         /// # let bytes: &[u8] = &[0x0E, 0x20, 0x54, 0x08, 0x12, 0x00, 0x00, 0x00, 0x2E, 0x46, 0x49, 0x54, 0x39, 0x04, 0x40, 0x00, 0x00, 0x14, 0x00, 0x02, 0xFD, 0x04, 0x86, 0x03, 0x01, 0x02, 0x00, 0x00, 0xCA, 0x9A, 0x3B, 0x8E, 0x20, 0xD3];\n\
         /// use zerofit::{Decoder, Record};\n\
         /// use zerofit_profile::Message;\n///\n\
         /// for record in Decoder::new(bytes) {\n\
         ///     if let Record::Data(msg) = record? {\n\
         ///         if let Message::Record(r) = Message::new(msg) {\n\
         ///             assert_eq!(r.heart_rate(), Some(142));\n\
         ///         }\n\
         ///     }\n\
         /// }\n\
         /// # Ok::<(), zerofit::Error>(())\n\
         /// ```\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n#[non_exhaustive]\n\
         pub enum Message<'a> {\n",
    );
    for m in messages {
        let name = camel(&m.name);
        let _ = writeln!(
            out,
            "    /// A `{}` message.\n    {name}({name}<'a>),",
            m.name
        );
    }
    out.push_str(
        "    /// A message this crate has no typed view for.\n    Other(DataMessage<'a>),\n}\n\n\
         impl<'a> Message<'a> {\n    \
         /// Wraps `msg` in its typed view.\n    #[must_use]\n    \
         pub fn new(msg: DataMessage<'a>) -> Self {\n        \
         match msg.global_message_number() {\n",
    );
    for m in messages {
        let name = camel(&m.name);
        let _ = writeln!(
            out,
            "            {} => Self::{name}({name}(msg)),",
            m.number
        );
    }
    out.push_str(
        "            _ => Self::Other(msg),\n        }\n    }\n\n    \
         /// The underlying raw message.\n    #[must_use]\n    \
         pub const fn raw(&self) -> &DataMessage<'a> {\n        match self {\n",
    );
    for m in messages {
        let _ = writeln!(out, "            Self::{}(m) => &m.0,", camel(&m.name));
    }
    out.push_str("            Self::Other(m) => m,\n        }\n    }\n}\n\n");
}

fn gen_info(out: &mut String, messages: &[Message]) -> Result<(), String> {
    out.push_str(
        "/// Field metadata for every message this crate covers, in profile order.\n\
         pub static MESSAGES: &[MessageInfo] = &[\n",
    );
    for m in messages {
        let _ = writeln!(out, "    MessageInfo::new({}, \"{}\", &[", m.number, m.name);
        for f in &m.fields {
            let (scale, offset) = f.single_scale_offset().unwrap_or((1.0, 0.0));
            let units = f
                .units
                .as_deref()
                .map_or("None".to_owned(), |u| format!("Some({u:?})"));
            let _ = writeln!(
                out,
                "        FieldInfo::new({}, \"{}\", \"{}\", {units}, {}, {}, {}),",
                f.number,
                f.name,
                f.field_type,
                float_lit(scale),
                float_lit(offset),
                f.array.is_some()
            );
        }
        // Field number -> position in the list above (u8::MAX if absent),
        // so `MessageInfo::field` is one load instead of a linear scan.
        let mut index = [u8::MAX; 256];
        for (i, f) in m.fields.iter().enumerate() {
            index[usize::from(f.number)] = u8::try_from(i)
                .ok()
                .filter(|&i| i != u8::MAX)
                .ok_or_else(|| format!("{} has too many fields for a u8 index", m.name))?;
        }
        let index: Vec<String> = index.iter().map(u8::to_string).collect();
        let _ = writeln!(out, "    ], &[{}]),", index.join(", "));
    }
    out.push_str("];\n");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names() {
        assert_eq!(camel("file_id"), "FileId");
        assert_eq!(camel("4iiiis"), "N4iiiis");
        assert_eq!(method("type"), "type_");
        assert_eq!(doc_text("a [N] <b>"), "a \\[N\\] &lt;b&gt;");
    }
}
